---
all:
  children:
    home-servers:
    home-bastion:

home-servers:
  hosts:
    hp1:
    hp2:
    hp3:
    tc1:

home-bastion:
  hosts:
    3bp:

k3s_cluster:
  children:
    server:
      hosts:
        hp3:
    agent:
      hosts:
        hp1:
        hp2:
        tc1:
