---
services:
  traefik:
    image: "{{ docker_traefik_image }}"
    container_name: "traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    command:
      - --providers.docker=true
      - --api.insecure=true


networks:
  default:
    name: "{{ docker_traefik_network }}"
    external: true
