---
- name: Postgres APT key 
  ansible.builtin.apt_key:
    url: "{{ docker_postgres_apt_key_url }}"
    state: present

- name: Postgres APT repository
  become: true
  ansible.builtin.apt_repository:
    codename: "{{ ansible_distribution_release }}"
    repo: deb http://apt.postgresql.org/pub/repos/apt/
          {{ ansible_distribution_release }}-pgdg main

- name: Postgres Install Client
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: postgresql-client-{{ docker_postgres_major_version }}
    state: present

- name: Postgres Install Psycopg
  ansible.builtin.pip:
    name: "{{ docker_postgres_psycopg2 }}"
