---
services:
  postgres:
    image: "{{ docker_postgres_image }}"
    container_name: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - /etc/postgresql:/etc/postgresql:ro
      - /etc/postgresql:/docker-entrypoint-initdb.d:ro
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_PASSWORD: '{{ docker_postgres_password }}'
      POSTGRES_DB: postgres
    ports:
      - 127.0.0.1:5432:5432
    labels:
      - traefik.tcp.routers.postgres.rule=Host(`postgres.docker.localhost`)
      - traefik.tcp.routers.postgres.service=postgres
      - traefik.tcp.services.postgres.loadbalancer.server.port=5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'postgres']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 0s

  postgres_server_exporter:
    image: '{{ docker_postgres_server_exporter_image }}'
    container_name: postgres_server_exporter
    environment:
      DATA_SOURCE_NAME: "{{ docker_postgres_server_exporter_datasource }}"

networks:
  default:
    name: "{{ docker_postgres_network }}"
    external: true
